<?php

    // HTTP STATUS CODE
    define('HTTP_STATUS_CODE_OK', 200);
    define('HTTP_STATUS_CODE_NOT_FOUND', 404);
    define('HTTP_STATUS__CODE_INTERNAL_SERVER_ERROR', 500);

    // HTTP STATUS MESSAGE
    define('HTTP_STATUS_MESSAGE_OK', 'OK');
    define('HTTP_STATUS_MESSAGE_NOT_FOUND', 'NOT FOUND');
    define('HTTP_STATUS_MESSAGE_INTERNAL_SERVER_ERROR', 'INTERNAL SERVER ERROR');


    